#!/usr/bin/env bash

if [ -z "$SAGE_LOCAL" ]; then
   echo >&2 "SAGE_LOCAL undefined ... exiting"
   echo >&2 "Maybe run 'sage -sh'?"
   exit 1
fi

echo "Removing previous versions of Definability."
rm -rf $SAGE_ROOT/local/lib/python/site-packages/definability*
rm -rf $SAGE_ROOT/local/lib/python2.7/site-packages/definability*

cd src

python setup.py install
if [ $? -ne 0 ]; then
    echo >&2 "Error installing Definability."
    exit 1
fi
