#!/bin/sh

export top_level=`pwd`

mkdir $top_level/src/
cd $top_level/src/
tar xzvf $top_level/LADR-2009-11A.tar.gz

echo "Building Prover9..."

cd $top_level/src/LADR-2009-11A/
make all

echo "Copying Prover9..."
for program in prover9 mace4 interpformat isofilter isofilter2 prooftrans;
do
  cp bin/$program $SAGE_LOCAL/bin/ua-$program
done

cd $top_level/src/
tar xzvf $top_level/uacalc.tar.gz

echo "Moving UACalc..."
mv uacalc $SAGE_LOCAL/bin/uacalc

mkdir $SAGE_ROOT/data
mkdir $SAGE_ROOT/data/univ_algebra

cd $top_level
# antes era cp logic/* $SAGE_ROOT/devel/sage/sage/logic
cp logic/* $SAGE_ROOT/src/sage/logic

